Repository fork-commit-merge/fork-commit-merge-web, pull requests merged in 2023-09, with the labels that each got.

#55 added new language description to components/Descriptions.tsx
  components/Descriptions.tsx
Labels: Extra Small

#56 mobile header behavior
  components/layout/Header.tsx
  styles/tailwind.css
Labels: Extra Small

#65 #62 issue: create more language components
  components/data/languageList.ts
  components/languageComponents/CrystalLanguage.tsx
  components/languageComponents/DLanguage.tsx
  components/languageComponents/ElmLanguage.tsx
  components/languageComponents/GroovyLanguage.tsx
  components/languageComponents/NimLangauge.tsx
  components/languageComponents/OctaveLanguage.tsx
  components/languageComponents/RescriptLanguage.tsx
  components/languageComponents/ScratchLanguage.tsx
  package-lock.json
  pages/languages/[lang].tsx
Labels: Extra Large

#66 [Snyk] Upgrade eslint-config-next from 13.4.12 to 13.4.18
  package-lock.json
  package.json
Labels: Extra Small

#67 [Snyk] Upgrade next from 13.4.12 to 13.4.18
  package-lock.json
  package.json
Labels: Extra Small

#68 [Snyk] Upgrade aws-sdk from 2.1424.0 to 2.1439.0
  package-lock.json
  package.json
Labels: Extra Small

#73 [Snyk] Upgrade eslint-config-next from 13.4.12 to 13.4.18
  package-lock.json
  package.json
Labels: Extra Small

#74 [Snyk] Upgrade next from 13.4.12 to 13.4.18
  package-lock.json
  package.json
Labels: Extra Small

#75 [Snyk] Upgrade aws-sdk from 2.1424.0 to 2.1440.0
  package-lock.json
  package.json
Labels: Extra Small

#76 [Snyk] Upgrade next-auth from 4.22.3 to 4.23.1
  package-lock.json
Labels: No Changes

#79 [Snyk] Upgrade next from 13.4.18 to 13.4.19
  package-lock.json
  package.json
Labels: Extra Small

#78 [Snyk] Upgrade eslint-config-next from 13.4.18 to 13.4.19
  package-lock.json
  package.json
Labels: Extra Small

#86 Fetch users to db
  components/index/IndexMain.tsx
  components/index/TopThreeContributors.tsx
  components/leaderboard/LeaderBoard.tsx
  package-lock.json
  package.json
  pages/api/topThreeUsers.js
  pages/api/topUsers.js
  types.ts
  utils/fetchTopThreeUsersByPullRequests.ts
  utils/fetchTopUsersByPullRequests.ts
  utils/fetchTopUsersFromDb.ts
Labels: Large

#91 Update Header.tsx
  components/layout/Header.tsx
Labels: Extra Small

#93 a fav icon was added to the project :)
  pages/_document.tsx
  public/fork-commit-merge-logo-favicon.png
Labels: Extra Small

#94 new languages added
  components/data/languageList.ts
  components/languageComponents/ObjectiveCLanguage.tsx
  components/languageComponents/PascalLanguage.tsx
  pages/languages/[lang].tsx
Labels: Medium

#104 [Snyk] Upgrade typescript from 5.1.6 to 5.2.2
  package-lock.json
  package.json
Labels: Extra Small

#105 [Snyk] Upgrade @ant-design/icons from 5.2.5 to 5.2.6
  package-lock.json
  package.json
Labels: Extra Small
